# Generated by Django 5.2.7 on 2025-10-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('moderator', 'Moderator'), ('editor', 'Editor')], default='author', max_length=20),
        ),
    ]
