# Generated by Django 5.2.7 on 2025-10-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
